{- DO NOT EDIT THIS FILE
   THIS FILE IS AUTOMAGICALLY GENERATED AND YOUR CHANGES WILL BE EATEN BY THE GENERATOR OVERLORD

   All changes should go into the Model file (e.g. App/Models/ExampleModel.hs)
-}

module App.Models.Bases.CommentsType where

import App.Models.Bases.Common
import Data.Maybe
import System.Time

-- The data type for this model
data Comments = Comments {
    author :: String,
    body :: Maybe String,
    commentId :: Maybe Int64,
    postId :: Int64
    } deriving (Eq, Show)

instance DatabaseModel Comments where
    tableName _ = "comments"

