{- DO NOT EDIT THIS FILE
   THIS FILE IS AUTOMAGICALLY GENERATED AND YOUR CHANGES WILL BE EATEN BY THE GENERATOR OVERLORD

   All changes should go into the Model file (e.g. App/Models/ExampleModel.hs)
-}

module App.Models.Bases.PostsType where

import App.Models.Bases.Common
import Data.Maybe
import Data.Time
import Data.Typeable

-- The data type for this model
data Posts = Posts {
    _id :: Maybe Integer,
    body :: String,
    created_at :: Maybe ZonedTime,
    title :: String
    } deriving (Show, Typeable)

instance DatabaseModel Posts where
    tableName _ = "posts"

