{- DO NOT EDIT THIS FILE
   THIS FILE IS AUTOMAGICALLY GENERATED AND YOUR CHANGES WILL BE EATEN BY THE GENERATOR OVERLORD

   All changes should go into the Model file (e.g. App/Models/ExampleModel.hs)
-}

module App.Models.Bases.PostsRelations where

import App.Models.Bases.Common
import qualified Database.HDBC as HDBC
import Data.Maybe
import System.Time

 -- Model imports
import App.Models.Bases.PostsType
import qualified App.Models.Bases.CommentsType as CommentsType
import qualified App.Models.Bases.CommentsFunctions as CommentsFunctions



import Turbinado.Environment.Types
import Turbinado.Environment.Database



class PostsHasCommentsForeignKey parent where
    findAllChildComments :: (HasEnvironment m) => parent -> m [CommentsType.Comments]

instance PostsHasCommentsForeignKey (Posts) where
    findAllChildComments p = CommentsFunctions.findAllWhere "post_id = ?" [HDBC.toSql $ _id p]







