{- DO NOT EDIT THIS FILE
   THIS FILE IS AUTOMAGICALLY GENERATED AND YOUR CHANGES WILL BE EATEN BY THE GENERATOR OVERLORD

   All changes should go into the Model file (e.g. App/Models/ExampleModel.hs)
-}

module App.Models.Bases.PostsRelations where

import App.Models.Bases.Common
import qualified Database.HDBC as HDBC
import Data.Maybe
import Data.Time

 -- Model imports
import App.Models.Bases.PostsType
import qualified App.Models.Bases.CommentsType as CommentsType
import qualified App.Models.Bases.CommentsFunctions as CommentsFunctions



import Turbinado.Environment.Types
import Turbinado.Environment.Database



findAllChildComments :: (HasEnvironment m) => Posts -> m [CommentsType.Comments]
findAllChildComments p = findAllWhere "post_id = ?" [HDBC.toSql $ _id p]







